templates: Update data licence information and attribution list
ThreeSixtyGiving/grantnav pull request #1094
Opened 2024-07-26 11:52 UTC by rhiaro

Updates the [datasets](https://grantnav.threesixtygiving.org/datasets/#reuse) page with attribution statements and licence information for data sources used to enhance grantnav data.

2024-07-26 16:30 UTC, rhiaro commented
Most of the failing links (which are just sites blocking automated requests) work using a GET rather than a HEAD, but it's a bit slower. One remaining one is something to do with the SSL cert at the NI charity commission.

The other: `FAILED grantnav/frontend/tests_functional.py::test_links[/grant/360G-LBFEW-99233] - AssertionError: http://localhost:52183/publisher/ is broken: 404 on page /grant/360G-LBFEW-99233` is as far as I can tell not related to my changes (and failing in some of the other open PRs too).

2024-08-01 11:52 UTC, michaelwood commented on grantnav/frontend/templates/datasets.html
> +          <li><a href="https://download.companieshouse.gov.uk/en_output.html">Companies House</a></li>
That would be good

2024-08-01 11:53 UTC, michaelwood commented on grantnav/frontend/tests_functional.py
> +    skip = ["#", "https://twitter.com/360Giving/", "mailto:grantnav@threesixtygiving.org", "https://insights.threesixtygiving.org/?url=https://grantnav.threesixtygiving.org/search.json%3F", "https://
? I'm not sure that is needed

2024-08-01 11:54 UTC, michaelwood commented on grantnav/frontend/tests_functional.py
> +                r = requests.get(link, headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36"})
I think we'd stick with HEAD as this should be much faster than actually retrieving the page content

2024-08-01 11:54 UTC, michaelwood commented on grantnav/frontend/templates/datasets.html
> +              <th>license</th>
Keep the capitals please

2024-08-01 11:55 UTC, michaelwood commented on grantnav/frontend/tests_functional.py
> +    skip = ["#", "https://twitter.com/360Giving/", "mailto:grantnav@threesixtygiving.org", "https://insights.threesixtygiving.org/?url=https://grantnav.threesixtygiving.org/search.json%3F", "https://
Rather we didn't have this one in there, is it definitely not working?

2024-09-03 15:05 UTC, michaelwood requested changes

2024-09-03 15:05 UTC, michaelwood commented on grantnav/frontend/tests_functional.py
>                                      ])
Could you squash this into c859f9a023694d8cf943fc3ddf29f7367da0f8e3 so that it isn't removed and added

2024-09-03 15:05 UTC, michaelwood commented on grantnav/frontend/tests_functional.py
> +                print(e)
Are the prints useful still?

2024-09-03 15:37 UTC, rhiaro commented on grantnav/frontend/tests_functional.py
> +                print(e)
Yeah they're useful if the test fails

2024-09-03 15:37 UTC, rhiaro commented on grantnav/frontend/tests_functional.py
>                                      ])
I plan to squash all of these commits on merge

2024-09-10 09:15 UTC, michaelwood approved these changes, later dismissed

2024-09-10 11:03 UTC, michaelwood approved these changes

2024-09-10 11:07 UTC, merged