Summary stats years update
ThreeSixtyGiving/grantnav pull request #776
Opened 2021-07-12 14:23 UTC by Lathrisk

Closes #771 
Closes #769

2021-07-12 14:25 UTC, Lathrisk commented
![](https://github.trello.services/images/mini-trello-icon.png) [Summary Stats updates: Years](https://trello.com/c/J76566pW/186-summary-stats-updates-years)

2021-07-19 09:04 UTC, Lathrisk commented
Updated to the following screenshot:

![search-summary-years](https://user-images.githubusercontent.com/517804/126133939-fb25ce9b-b3ff-47dc-960b-a413c0c1d2ce.png)

2021-07-19 15:54 UTC, michaelwood requested changes

2021-07-19 15:54 UTC, michaelwood commented on grantnav/frontend/templatetags/graphs.py
> +        x2 = deepcopy(x)
Can we call this something more descriptive like  `x_with_aggregated_first` or something along those lines

2021-07-19 16:12 UTC, michaelwood approved these changes

2021-07-20 08:54 UTC, merged