widgets: move sort dropdown to settings
ThreeSixtyGiving/grantnav pull request #932
Opened 2022-11-28 15:43 UTC by codemacabre

## Summary
+ Add sort dropdown to widget builder settings.
+ Remove sort from widget builder preview to prevent confusion

Fixes: https://github.com/ThreeSixtyGiving/grantnav/issues/923

## Verify
1. Visit the widget builder
2. Make a search query and select a sort order using the "Sort by" dropdown
3. The page should reload with the selected sort applied, and reflected in the preview
4. The preview should no longer have a "Sort By" dropdown
5. Copy code and embed elsewhere to verify the sort order is preserved

2022-11-28 18:22 UTC, michaelwood commented
I had a quick test. This looks really good @codemacabre 

@mariongalley I suggested we remove the order-by in the widget itself as this could be quite confusing / undesirable if the user has deliberately chosen an order-by setting.

![image](https://user-images.githubusercontent.com/493697/204351662-b75ae079-2d77-41a1-a4c7-8ed3faf2d9b7.png)

2022-11-28 18:25 UTC, michaelwood commented
Just seen your comment on #923 . If you'd definitely still like it on the widget itself, maybe we call it "Default order by" in the settings pane.

2022-11-29 09:12 UTC, mariongalley commented
> Just seen your comment on #923 . If you'd definitely still like it on the widget itself, maybe we call it "Default order by" in the settings pane.

That sounds good - yeah I think one of the things the publishers were most keen on was for the widgets to be dynamic, and this removes one of the only things the user interacting with the widget can change which seems a shame

2022-11-29 11:58 UTC, codemacabre commented
I've returned the dropdown to the widget, and made the dropdown's title customisable so we can change it on the widgets page. While I was there, I've also added the 360Insights button as requested in https://github.com/ThreeSixtyGiving/grantnav/issues/918, so this should complete both issues.

2022-11-29 12:05 UTC, michaelwood requested changes
Great - Just one thing missing is that the git submodule for 360-ds is now pointing at an old commit and needs to be at the new HEAD of the 360-ds repository

2022-11-29 12:20 UTC, michaelwood approved these changes

2022-11-29 12:20 UTC, merged